### ISSUE TITLE
Font files 

### ISSUE THREAD

**Issue by dreyz** [cichy380/html-starter-bs4-webpack#1]
Hello! How to work with custom fonts like this?
Module not found: Error: Can't resolve '../../fonts/GothamProRegular/GothamProRegular.woff'
_fonts.scss
```
@font-face {
    font-family: "GothamProRegular";
    src: url("../../fonts/GothamProRegular/GothamProRegular.eot");
    src: url("../../fonts/GothamProRegular/GothamProRegular.eot?#iefix")format("embedded-opentype"), url("../../fonts/GothamProRegular/GothamProRegular.woff") format("woff"), url("../../fonts/GothamProRegular/GothamProRegular.ttf") format("truetype");
    font-style: normal;
    font-weight: normal;
}
```

**Comment by cichy380** [comment]
I added [file-loader](https://github.com/webpack-contrib/file-loader) [resolve-url-loader](https://github.com/bholloway/resolve-url-loader) and for font files, so `git pull` and install new dependency by `yarn` or `npm install`

https://github.com/cichy380/html-starter-bs4-webpack/commit/285604e0cdcd3ff16ba88fe482f21ad77355ef87
