### ISSUE TITLE
.gif images can't be processed.

### ISSUE THREAD

**Issue by immanuelsun** [cichy380/html-starter-bs4-webpack#2]
In my `index.html`, I added a gif file with src as `/images/loader.gif`. Webpack runs just fine, but the gif image will not show like `/images/logo.jpg`. Can't figure out why.

**Comment by cichy380** [comment]
I also tested with GIF animated pictures. Works fine for me.
Please, make sure that image path is correct. If you placed your `loader.gif` file in `assets/images/` folder - in `assets/html/index.html` file you should use image tag like this: `<img src="./../images/loader.gif">`
